# Generated by Django 4.2.7 on 2025-06-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_sat',
            new_name='toc',
        ),
    ]
